name: build-v2

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "dev/V2File"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dev/V2File
          push: true
          platforms: linux/amd64, linux/arm64, linux/s390x, linux/arm
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-warp-socks:pre-v2
      -
        name: Sleep and replace
        shell: bash
        run: |
          sleep 60
          sed -i 's/meta/pre-v2/g' Dockerfile
          cat Dockerfile
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64, linux/arm64, linux/s390x, linux/arm
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-warp-socks:v2