name: build-v2

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "dev/Meta"
      - "Dockerfile"
      - "entrypoint.sh"

jobs:
  build-pre-v2:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push meta
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dev/Meta
          push: true
          platforms: linux/amd64, linux/arm64, linux/s390x, linux/arm
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-warp-socks:meta
      -
        name: Build and push meta_v2
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dev/Meta
          push: true
          platforms: linux/amd64, linux/arm64, linux/s390x, linux/arm
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-warp-socks:meta_v2
      -
        name: Build and push v2
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64, linux/arm64, linux/s390x, linux/arm
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-warp-socks:v2