name: Refer

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

on:
  workflow_call:
    inputs:
      api:
        description: 'api test endpoint'
        required: True
        default: 'http://127.0.0.1:6991/reg'
        type: string
      ref:
        description: 'refer_account_id'
        required: True
        default: 'false'
        type: string
      key:
        description: 'refer_account_license'
        required: True
        default: 'false'
        type: string
    outputs:
      id:
        description: "original account id"
        value: ${{ jobs.call.outputs.id }}
      key:
        description: "original account key"
        value: ${{ jobs.call.outputs.token }}

jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: refer
        if: ${{ inputs.ref != 'false' }}
        run: |
          WARP_API_TEST_REG="${{ inputs.api }}"

          key="$(cat /dev/urandom | head -c 10 | sha256sum | head -c 43)="
          referrer="${{ inputs.ref }}"
          referrer_key"${{ inputs.key }}"
          tos=$(TZ=UTC+2 date "+%Y-%m-%dT%H:%M:%S.691-02:00")
          locale="es_ES"
          model="RTX 6090Ti"
          type="HPC"

          json="{
          \"key\": \"$key\", \
          \"referrer\": \"$referrer\", \
          \"tos\": \"$tos\", \
          \"locale\": \"$locale\", \
          \"model\": \"$model\", \
          \"type\": \"$type\" \
          }"
          curl -X POST -fsSL $WARP_API_TEST_REG \
          -H 'authority: cloudflareclient.com' \
          -H 'host: api.cloudflareclient.com' \
          -H 'User-Agent: okhttp/4.12.1' \
          -H 'accept-encoding: gzip' \
          -H 'accept-language: en-US,en;q=0.9' \
          -H 'content-type: application/json; charset=UTF-8' \
          -H 'connection: Keep-Alive' \
          -H 'origin: https://cloudflareclient.com' \
          -H 'referer: https://warp.plus' \
          -H 'user-agent: okhttp/4.12.1' \
          --compressed \
          --data "$json"
          echo id=$referrer key=$referrer_key >> $GITHUB_OUTPUT
        name: Refer Test Account
        shell: bash