name: Reg

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WARP_API_TEST_REG: ${{ secrets.WARP_API_TEST_REG }}
  WARP_DEFAULT: ${{ secrets.WARP_DEFAULT }}
  CARGO_TERM_COLOR: always

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        description: 'refer_account_id'
        required: false
        default: 'false'
        type: string
jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: register
        run: |
          ref=${{ inputs.ref }}
          key="$(cat /dev/urandom | head -c 10 | sha256sum | head -c 43)="
          tos=$(TZ=UTC+1 date "+%Y-%m-%dT%H:%M:%S.691-01:00")
          locale="fr-FR"
          model="iPhone15,1"
          type="IOS"
          json="{
          \"key\": \"$key\", \
          \"referrer\": \"$WARP_DEFAULT\", \
          \"tos\": \"$tos\", \
          \"locale\": \"$locale\", \
          \"model\": \"$model\", \
          \"type\": \"$type\" \
          }

          if [ $ref = "false" ]; then
            echo $json
          fi
        name: Register Test Account
        shell: bash