name: Reg

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WARP_API_TEST_REG: ${{ secrets.WARP_API_TEST_REG }}
  WARP_DEFAULT: ${{ secrets.WARP_DEFAULT }}
  CARGO_TERM_COLOR: always

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        description: 'refer_account_id'
        required: false
        default: 'false'
        type: string
jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: register
        run: |
          locale="fr-FR"
          model="iPhone15,1"
          type="IOS"
        name: Register Test Account
        shell: bash