name: verify-all

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TRACE: "https://www.cloudflare.com/cdn-cgi/trace"
  SOCKS: "socks5h://127.0.0.1"
  PASS: "monius:passwd"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["build-v2"]
    types:
      - completed

jobs:
  v1:
    runs-on: ubuntu-latest
    env:
      name: ${{ github.job }}
      port: 6091
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
          curl -fsSL bit.ly/warp_socks | sh -s -- "$name" "linux/amd64" "1" "$port"
          date && sleep 60 && docker ps -a && date && docker logs "$name"
      - id: check
        run: echo trace=$(curl -v -U $PASS -x "$SOCKS:$port" -fsSL $TRACE | grep -w "warp=on") >> $GITHUB_OUTPUT
      - run: echo "The proxy status is ${{ steps.check.outputs.trace }}"
      - uses: lhotari/action-upterm@v1
        if: ${{ steps.check.outputs.trace != 'warp=on' }}

