name: verify-all

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["build-v2"]
    types:
      - completed

jobs:
  v1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
          curl -fsSL bit.ly/warp_socks | sh -s -- "$name" "linux/amd64" "1" "$port"
          date && sleep 60 && docker ps -a && date && docker logs "$name"
        env:
          name: ${{ github.job }}
          port: 6091
      - id: check
        run: |
          trace=$(curl -v -U "monius:passwd" -x "socks5h://127.0.0.1:9091" -fsSL "https://www.cloudflare.com/cdn-cgi/trace" | grep -w "warp=on")
          echo ::set-output name=trace::$trace
      - run: echo "The proxy status is ${{ steps.check.outputs.trace }}"
      - uses: lhotari/action-upterm@v1
        if: ${{ steps.check.outputs.trace != 'warp=on' }}

