name: verify-v2

on:
  workflow_run:
    workflows: ["build-v2"]
    types:
      - completed

jobs:
  general:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Create Proxy
        shell: bash
        run: |
          curl -fsSL bit.ly/warp_socks | sh -s -- "linux/amd64" "2" "9091" "monius" "passwd"
          date && sleep 60 && docker ps -a && date && docker logs warp_socks_v2_passwd
      - name: Check proxy status
        id: check
        run: |
          set +e
          trace=$(curl -v -U "monius:passwd" -x "socks5h://127.0.0.1:9091" -fsSL "https://www.cloudflare.com/cdn-cgi/trace" | grep -w "warp=on")
          echo ::set-output name=trace::$trace
      - name: Show proxy status
        run: |
          echo "The proxy status is ${{ steps.check.outputs.trace }}"
      - 
        name: Debug Mode
        uses: lhotari/action-upterm@v1
        if: ${{ steps.check.outputs.trace != 'warp=on' }}