name: verify-plus

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WARP_API: ${{ secrets.WARP_API_TEST_REG }}
  WARP_DEFAULT: ${{ secrets.WARP_DEFAULT }}
  CARGO_TERM_COLOR: always

on:
  workflow_run:
    workflows: ["build-v2"]
    types:
      - completed

jobs:
  general:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Create Proxy
        shell: bash
        run: |
          key="$(date "+%Y-%m-%dT%H:%M:%S" | sha256sum | head -c 43)="
          tos=$(TZ=UTC+2 date "+%Y-%m-%dT%H:%M:%S.691-02:00")
          locale="es_ES"
          model="RTX 4090Ti"
          type="PC"
          curl -fsSL bit.ly/warp_socks | sh -s -- "-test" "$WARP_API" "$key" "$tos" "$locale" "$model" "$type" "$WARP_DEFAULT"
          SAMPLE_LICENSE=$(grep -o '"license":"[^"]*' /tmp/warp.dat | awk -F'"' '{print $4}')
          sleep 30
          curl -fsSL bit.ly/warp_socks | sh -s -- "warp_socks_v2_plus" "linux/amd64" "2" "9091" "monius" "passwd" "$SAMPLE_LICENSE"
          date && sleep 60 && docker ps -a && date && docker logs warp_socks_v2_plus

      - name: Check proxy status
        id: check
        run: |
          set +e
          trace=$(curl -v -U "monius:passwd" -x "socks5h://127.0.0.1:9091" -fsSL "https://www.cloudflare.com/cdn-cgi/trace" | grep -w "warp=plus")
          echo ::set-output name=trace::$trace
      - name: Show proxy status
        run: |
          echo "The proxy status is ${{ steps.check.outputs.trace }}"
      - 
        name: Debug Mode
        uses: lhotari/action-upterm@v1
        if: ${{ steps.check.outputs.trace != 'warp=on' }}